name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  postgres:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.2]
        gemfile: [ar_7_1, ar_7_2]
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: odbc_test
        ports: ['5432:5432']
    env:
      DB_DATABASE: odbc_test
      DB_USER: postgres
      DB_PASSWORD: password
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_PATH_RELATIVE_TO_CWD: true
    steps:
      - uses: actions/checkout@v3
      - name: Install ODBC drivers
        run: sudo apt-get install unixodbc unixodbc-dev odbc-postgresql
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle install
      - name: driver setup
        run: ./bin/ci-setup
      - name: Run tests
        env:
          DB: "postgres"
          CONN_STR: "DRIVER={PostgreSQL ANSI};SERVER=127.0.0.1;PORT=5432;DATABASE=${{ env.DB_DATABASE }};UID=${{ env.DB_USER }};password=${{ env.DB_PASSWORD }}"
        run: bundle exec rake test
