name: Ruby

on:
  push:
    # branches: [ master ]
  pull_request:

jobs:
  postgres:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6]
        gemfile:
          - ar_5_2
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: odbc_test
        ports: ['5432:5432']
    env:
      DB_DATABASE: odbc_test
      DB_USER: postgres
      DB_PASSWORD: password
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Install ODBC drivers
        run: sudo apt-get install unixodbc unixodbc-dev odbc-postgresql
      - name: Install dependencies
        run: bundle install
      - name: driver setup
        run: ./bin/ci-setup
      - name: Run tests
        env:
          DB: "postgres"
          CONN_STR: "DRIVER={PostgreSQL ANSI};SERVER=127.0.0.1;PORT=5432;DATABASE=${{ env.DB_DATABASE }};UID=${{ env.DB_USER }};password=${{ env.DB_PASSWORD }}"
        run: bundle exec rake test
  # mysql:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       ruby: [3.2]
  #   env:
  #     DB_DATABASE: odbc_test
  #     DB_USER: root
  #     DB_PASSWORD: root
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Ruby
  #       uses: ruby/setup-ruby@v1
  #       with:
  #         bundler-cache: true
  #         ruby-version: ${{ matrix.ruby }}
  #     - name: Install ODBC drivers
  #       run: sudo apt-get install unixodbc unixodbc-dev mysql-client
  #     - name: Set up MySQL
  #       run: |
  #         sudo /etc/init.d/mysql start
  #         mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
  #     - name: Install dependencies
  #       run: bundle install
  #     - name: Run tests
  #       env:
  #         DB: "mysql"
  #         CONN_STR: "DRIVER=MySQL;SERVER=127.0.0.1;DATABASE=${{ env.DB_DATABASE }};USER=${{ env.DB_USER }};PASSWORD=${{ env.DB_PASSWORD }};"
  #       run: ./bin/ci-setup && bundle exec rake test
